<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="Dell123" name="com.intBanking.testCases.TC_LoginTest_002" tests="4" failures="0" timestamp="2023-04-27T21:57:37 IST" time="31.426" errors="1">
  <testcase name="setup" time="31.426" classname="com.intBanking.testCases.TC_LoginTest_002">
    <error type="java.lang.NoSuchMethodError" message="org.openqa.selenium.WebDriver$Timeouts.implicitlyWait(Ljava/time/Duration;)Lorg/openqa/selenium/WebDriver$Timeouts;">
      <![CDATA[java.lang.NoSuchMethodError: org.openqa.selenium.WebDriver$Timeouts.implicitlyWait(Ljava/time/Duration;)Lorg/openqa/selenium/WebDriver$Timeouts;
at com.intBanking.testCases.BaseClass.setup(BaseClass.java:58)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- setup -->
  <system-out/>
  <testcase name="loginDDT" time="0.000" classname="com.intBanking.testCases.TC_LoginTest_002">
    <skipped/>
  </testcase> <!-- loginDDT -->
  <system-out/>
  <testcase name="loginDDT" time="0.000" classname="com.intBanking.testCases.TC_LoginTest_002">
    <skipped/>
  </testcase> <!-- loginDDT -->
  <system-out/>
  <testcase name="loginDDT" time="0.000" classname="com.intBanking.testCases.TC_LoginTest_002">
    <skipped/>
  </testcase> <!-- loginDDT -->
  <system-out/>
</testsuite> <!-- com.intBanking.testCases.TC_LoginTest_002 -->
